name: scn_easy
description: SCN Easy App
publish_to: 'none'

# android new version 2023-11-14 09:32
version: 1.4.33+42

# ios new version 2023-11-14 09:32
#version: 1.4.24+32

# old version check before deploy
# android 1.4.31+40
# ios 1.4.22+30

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.3.3 # added by thin
  get: ^4.6.5
  logger: ^2.0.2+1 # added by thin
  pretty_dio_logger: ^1.3.1 # added by thin
  shared_preferences: ^2.2.0
  connectivity: ^3.0.6
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  path_provider: ^2.1.0
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  flutter_typeahead: ^4.6.2
  flutter_screenutil: ^5.9.0
  shimmer_animation: ^2.1.0+1
  permission_handler: ^11.0.1
#  flutter_svg_provider: ^1.0.4
  ntp: ^2.0.0
  url_launcher: ^6.1.12
  http: ^1.1.0
  pointer_interceptor: ^0.9.3+4
  cached_network_image: ^3.2.3
  http_parser: ^4.0.2
  pubnub: ^4.2.4
  intl: any
  #if update this to high version ios will error
#  flutter_super_html_viewer: ^0.0.2
  app_version_update: ^4.0.1
  font_awesome_flutter: ^10.5.0
  awesome_dialog: ^2.1.1
  screenshot: ^2.1.0
  share: ^2.0.4
  overlay_loader_with_app_icon: ^0.0.3
  image_picker: ^1.0.2
  simple_html_css: ^4.0.0
  flutter_html: any
  extended_text: ^11.0.1
  auto_size_text: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  pinput: ^4.0.0
  timer_count_down: ^2.2.2
  selectable_autolink_text: ^2.6.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  jwt_decoder: ^2.0.1
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/images/
    - assets/images/animals/
    - assets/lotto/img/
    - assets/new_design/
    - assets/lotto/banks/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: NotoSansLao
      fonts:
        - asset: assets/font/NotoSansLao-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansLao-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansLao-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansLao-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansLao-Black.ttf
          weight: 900
    - family: TimeNewRo
      fonts:
        - asset: assets/font/timesNewRomanBold.ttf
    - family: NotoColorEmoji
      fonts:
        - asset: assets/font/NotoColorEmoji-Regular.ttf